import pygame

PLAYER_ROCK_BUTTON = pygame.K_KP1
PLAYER_PAPER_BUTTON = pygame.K_KP2
PLAYER_SCISSORS_BUTTON = pygame.K_KP3

ENEMY_ROCK_BUTTON = pygame.K_a
ENEMY_PAPER_BUTTON = pygame.K_s
ENEMY_SCISSORS_BUTTON = pygame.K_d
